-- CREATE THE USER --

CREATE ROLE "user_pharmacy" WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'user';

-- DROP DATABASE "Pharmacy"; (if needed)

-- CREATE THE DATABASE --

CREATE DATABASE "Pharmacy"
    WITH 
    OWNER = user_pharmacy
    ENCODING = 'UTF8'
    LC_COLLATE = 'French_France.1252'
    LC_CTYPE = 'French_France.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

-- GRANT USAGE PRIVILEGES TO THE USER --

ALTER DEFAULT PRIVILEGES
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO user_pharmacy;